input {
    tcp {
        port => 5000
        codec => json_lines
    }
}

filter {
    mutate {
        add_field => {
            "ambiente" => "prod"
            "stack" => "oleiloeiro"
        }
    }
}

output {
    elasticsearch {
        hosts => ["http://elasticsearch:9200"]
        index => "oleiloeiro-logs-%{+YYYY.MM.dd}"

        ilm_enabled => false
        manage_template => false
        ecs_compatibility => v8
        sniffing => false
        timeout => 30
        pool_max => 1000
        pool_max_per_route => 100
    }

    stdout {
        codec => rubydebug
    }
}